### ISSUE TITLE
To Research: Find better way for creating session Id

### ISSUE THREAD

**Issue by bostud** [duyixian1234/fastapi-redis-session#2]
https://github.com/duyixian1234/fastapi-redis-session/blob/ae4c4e9c5270bbbcd87aa64edc41a9c8a90dba12/fastapi_redis_session/session.py#L23

This way can be used when you have as much 10k session records.
For better performance should be used algorithm which provides calculating sessionId, but not random creating and check until find free.

**Comment by duyixian1234** [comment]
It's a good question. 
Keeping randomly creating a session id until find a legal one is a little stupid but safe enough.
We'd better use a good algorithm to generate session ids such as snowflower algorithm which ensures generate unique ids.

While as the example code show,

```python
from fastapi_redis_session.config import basicConfig
basicConfig(
    redisURL="redis://localhost:6379/1",
    sessionIdName="sessionId",
    sessionIdGenerator=lambda: str(random.randint(1000, 9999)),
    expireTime=timedelta(days=1),
    )
```

users can use their custom algorithms to generate session ids (I think it is a reasonable requirement ), and not every algorithm generates completely unique ids.

Maybe we should find a better way to generate session ids safe and  efficiently.

**Comment by bostud** [comment]
Yeah
Users can use their own algorithm for sessionId creation
But if they would not - performance will go down as fast as much user will have sessions

so better use digits iterator at least, like binary search 
Ex, Check first key “100_some_hash”
If exists- multiply it and try again with key 200_some_hash
